Repository w0l1d/TalibHub, pull requests merged in 2023-12, with the labels that each got.

#6 #5 added user and its child models
  backend/src/main/java/org/ilisi/backend/model/Manager.java
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/model/User.java
Labels: good first issue

#11 #9 added user details service
  backend/src/main/java/org/ilisi/backend/repository/UserRepository.java
Labels: good first issue

#17 7 add login UI
  frontend/.prettierrc
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.routes.ts
  frontend/src/app/pages/login/login.component.css
  frontend/src/app/pages/login/login.component.html
  frontend/src/app/pages/login/login.component.spec.ts
  frontend/src/app/pages/login/login.component.ts
  frontend/src/styles.css
  frontend/tailwind.config.js
Labels: integration

#15 Create maven.yml
  .github/workflows/maven.yml
  backend/pom.xml
  backend/src/test/java/org/ilisi/backend/TestBackendApplication.java
Labels: good first issue

#18 W0l1d patch 1 added build test workflow
  .github/workflows/maven.yml
Labels: bug

#19 16 staging authentification intergration backend frontend
  backend/compose.yaml
  backend/pom.xml
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/auth/JwtAuthFilter.java
  backend/src/main/java/org/ilisi/backend/controller/AuthenticationController.java
  backend/src/main/java/org/ilisi/backend/services/AuthenticationService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/org/ilisi/backend/BackendApplicationTests.java
  backend/src/test/java/org/ilisi/backend/TestBackendApplication.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerUnitTest.java
  frontend/.prettierrc
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.config.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/pages/login/login.component.css
  frontend/src/app/pages/login/login.component.html
  frontend/src/app/pages/login/login.component.spec.ts
  frontend/src/app/pages/login/login.component.ts
  frontend/src/app/services/auth.service.spec.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/environments/environment.development.ts
  frontend/src/environments/environment.ts
  frontend/src/styles.css
  frontend/tailwind.config.js
Labels: integration

#20 4 spring security integration
  backend/compose.yaml
  backend/pom.xml
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/auth/JwtAuthFilter.java
  backend/src/main/java/org/ilisi/backend/controller/AuthenticationController.java
  backend/src/main/java/org/ilisi/backend/dto/AuthRequestDTO.java
  backend/src/main/java/org/ilisi/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/org/ilisi/backend/model/Session.java
  backend/src/main/java/org/ilisi/backend/model/User.java
  backend/src/main/java/org/ilisi/backend/repository/SessionRepository.java
  backend/src/main/java/org/ilisi/backend/security/JwtProperties.java
  backend/src/main/java/org/ilisi/backend/security/SecurityConfig.java
  backend/src/main/java/org/ilisi/backend/services/AuthenticationService.java
  backend/src/main/java/org/ilisi/backend/services/JwtService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/org/ilisi/backend/BackendApplicationTests.java
  backend/src/test/java/org/ilisi/backend/TestBackendApplication.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerUnitTest.java
  frontend/.prettierrc
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.config.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/pages/login/login.component.css
  frontend/src/app/pages/login/login.component.html
  frontend/src/app/pages/login/login.component.spec.ts
  frontend/src/app/pages/login/login.component.ts
  frontend/src/app/services/auth.service.spec.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/environments/environment.development.ts
  frontend/src/environments/environment.ts
  frontend/src/styles.css
  frontend/tailwind.config.js
Labels: good first issue

#26 24 backend code refactor and cleaning
  backend/src/main/java/org/ilisi/backend/auth/JwtAuthFilter.java
  backend/src/main/java/org/ilisi/backend/controller/AuthenticationController.java
  backend/src/main/java/org/ilisi/backend/controller/StudentController.java
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
  backend/src/main/java/org/ilisi/backend/exception/AuthenticationFailedException.java
  backend/src/main/java/org/ilisi/backend/exception/EntityNotFoundException.java
  backend/src/main/java/org/ilisi/backend/exception/GlobalAppException.java
  backend/src/main/java/org/ilisi/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/org/ilisi/backend/exception/InvalidTokenException.java
  backend/src/main/java/org/ilisi/backend/model/Manager.java
  backend/src/main/java/org/ilisi/backend/model/Profile.java
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/repository/InstitutRepository.java
  backend/src/main/java/org/ilisi/backend/repository/ProfileRepository.java
  backend/src/main/java/org/ilisi/backend/security/SecurityConfig.java
  backend/src/main/java/org/ilisi/backend/service/AuthenticationService.java
  backend/src/main/java/org/ilisi/backend/service/JwtService.java
  backend/src/main/java/org/ilisi/backend/service/ProfileService.java
  backend/src/main/java/org/ilisi/backend/service/StudentService.java
  backend/src/test/java/org/ilisi/backend/BackendApplicationTests.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerUnitTest.java
  backend/src/test/java/org/ilisi/backend/repositoryTests/UserRepositoryTest.java
  backend/src/test/java/org/ilisi/backend/service/ProfileServiceTests.java
  backend/src/test/java/org/ilisi/backend/service/StudentServiceTests.java
Labels: enhancement

#25 #21 Access token is sent with every http request.
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/controller/StudentController.java
  backend/src/main/java/org/ilisi/backend/exception/InvalidTokenException.java
  backend/src/main/java/org/ilisi/backend/security/JwtAuthFilter.java
  backend/src/main/java/org/ilisi/backend/security/SecurityConfig.java
  backend/src/main/java/org/ilisi/backend/service/JwtService.java
  backend/src/main/resources/application-dev.yml
  frontend/src/app/app.config.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/interceptors/token.interceptor.spec.ts
  frontend/src/app/interceptors/token.interceptor.ts
  frontend/src/app/models/token.ts
  frontend/src/app/pages/home/home.component.css
  frontend/src/app/pages/home/home.component.html
  frontend/src/app/pages/home/home.component.spec.ts
  frontend/src/app/pages/home/home.component.ts
  frontend/src/app/pages/login/login.component.ts
  frontend/src/app/services/auth.service.ts
Labels: enhancement, good first issue

#30 #29 refactor and clean frontend code
  frontend/src/app/interceptors/token.interceptor.ts
  frontend/src/app/pages/login/login.component.ts
  frontend/src/app/services/auth.service.ts
Labels: enhancement

#32 31 integration test for profile management
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
  backend/src/main/java/org/ilisi/backend/dto/EducationDto.java
  backend/src/main/java/org/ilisi/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/model/User.java
  backend/src/main/java/org/ilisi/backend/service/ProfileService.java
  backend/src/main/java/org/ilisi/backend/service/StudentService.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerUnitTests.java
  backend/src/test/java/org/ilisi/backend/controller/StudentControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/StudentProfileControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/StudentProfileControllerUnitTests.java
  backend/src/test/java/org/ilisi/backend/repository/UserRepositoryTests.java
  backend/src/test/java/org/ilisi/backend/service/ProfileServiceTests.java
  backend/src/test/java/org/ilisi/backend/service/StudentServiceTests.java
Labels: enhancement, good first issue

#37 36 make the profile dynamic
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
  backend/src/main/java/org/ilisi/backend/repository/ProfileRepository.java
  backend/src/main/java/org/ilisi/backend/service/ProfileService.java
  backend/src/main/resources/application-dev.yml
  frontend/src/app/components/layout/layout.component.html
  frontend/src/app/components/layout/layout.component.ts
  frontend/src/app/interceptors/token.interceptor.ts
  frontend/src/app/models/education.ts
  frontend/src/app/models/experience.ts
  frontend/src/app/models/institut.ts
  frontend/src/app/models/profile.ts
  frontend/src/app/models/student.ts
  frontend/src/app/models/user.ts
  frontend/src/app/pages/home/home.component.ts
  frontend/src/app/pages/login/login.component.html
  frontend/src/app/pages/login/login.component.ts
  frontend/src/app/pages/student-profile/student-profile.component.css
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/app/services/institut.service.spec.ts
  frontend/src/app/services/institut.service.ts
  frontend/src/app/services/student-profile.service.spec.ts
  frontend/src/app/services/student-profile.service.ts
Labels: good first issue
