Repository w0l1d/TalibHub, pull requests merged in 2024-01, with the labels that each got.

#41 39 add education modal component
  backend/src/main/java/org/ilisi/backend/controller/InstitutController.java
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
  backend/src/main/java/org/ilisi/backend/service/ProfileService.java
  backend/src/test/java/org/ilisi/backend/controller/StudentProfileControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/StudentProfileControllerUnitTests.java
  backend/src/test/java/org/ilisi/backend/service/ProfileServiceTests.java
  frontend/src/app/components/education-modal/education-modal.component.css
  frontend/src/app/components/education-modal/education-modal.component.html
  frontend/src/app/components/education-modal/education-modal.component.spec.ts
  frontend/src/app/components/education-modal/education-modal.component.ts
  frontend/src/app/components/experience-modal/experience-modal.component.css
  frontend/src/app/components/experience-modal/experience-modal.component.html
  frontend/src/app/components/experience-modal/experience-modal.component.spec.ts
  frontend/src/app/components/experience-modal/experience-modal.component.ts
  frontend/src/app/models/education.ts
  frontend/src/app/models/experience.ts
  frontend/src/app/models/institut.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/student-profile.service.ts
Labels: enhancement, good first issue

#40 38 imtegrate datatable
  backend/pom.xml
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/config/DataTablesConfiguration.java
  backend/src/main/java/org/ilisi/backend/controller/StudentController.java
  backend/src/main/java/org/ilisi/backend/repository/EducationRepository.java
  backend/src/main/java/org/ilisi/backend/repository/ExperienceRepository.java
  backend/src/main/java/org/ilisi/backend/repository/InstitutRepository.java
  backend/src/main/java/org/ilisi/backend/repository/ProfileRepository.java
  backend/src/main/java/org/ilisi/backend/repository/SessionRepository.java
  backend/src/main/java/org/ilisi/backend/repository/StudentRepository.java
  backend/src/main/java/org/ilisi/backend/repository/UserRepository.java
  backend/src/main/java/org/ilisi/backend/service/StudentService.java
  backend/src/test/java/org/ilisi/backend/controller/StudentControllerIntegrationTests.java
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/components/data-table/data-table.component.css
  frontend/src/app/components/data-table/data-table.component.html
  frontend/src/app/components/data-table/data-table.component.ts
  frontend/src/app/components/data-table/student-table-columns.ts
  frontend/src/app/components/layout/layout.component.html
  frontend/src/app/models/student.ts
  frontend/src/app/models/user.ts
  frontend/src/app/pages/student-management/student-management.component.html
  frontend/src/app/pages/student-management/student-management.component.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/services/student.service.spec.ts
  frontend/src/app/services/student.service.ts
  frontend/src/styles.css
Labels: good first issue

#42 38 imtegrate datatable - fix interceptor
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  frontend/src/app/components/data-table/data-table.component.ts
  frontend/src/app/pages/student-management/student-management.component.ts
  frontend/src/app/services/student.service.ts
Labels: bug, enhancement

#45 44 student deep search by text keyword using specifications
  backend/pom.xml
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/controller/StudentController.java
  backend/src/main/java/org/ilisi/backend/model/Education.java
  backend/src/main/java/org/ilisi/backend/model/Experience.java
  backend/src/main/java/org/ilisi/backend/model/Profile.java
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/model/User.java
  backend/src/main/java/org/ilisi/backend/service/StudentService.java
  backend/src/main/java/org/ilisi/backend/specs/ProfileSpecifications.java
  backend/src/main/java/org/ilisi/backend/specs/SpecUtils.java
  backend/src/main/java/org/ilisi/backend/specs/StudentSpecifications.java
  backend/src/test/java/org/ilisi/backend/controller/StudentProfileControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/specification/StudentSpecsTests.java
Labels: good first issue

#48 44 searchng profiles by query
  backend/src/main/java/org/ilisi/backend/controller/StudentController.java
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
Labels: enhancement, good first issue

#51 #46 added search for profiles
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/service/StudentService.java
  frontend/src/app/components/layout/layout.component.html
  frontend/src/app/components/layout/layout.component.ts
  frontend/src/app/pages/home/home.component.html
  frontend/src/app/pages/home/home.component.ts
  frontend/src/app/services/student-profile.service.ts
Labels: good first issue

#54 #49 added profile information consulting
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
  frontend/src/app/app.routes.ts
  frontend/src/app/pages/home/home.component.html
  frontend/src/app/pages/home/home.component.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/student-profile.service.ts
Labels: good first issue

#57 56 add publications management
  backend/src/main/java/org/ilisi/backend/config/JacksonConfiguration.java
  backend/src/main/java/org/ilisi/backend/config/UserDeserializer.java
  backend/src/main/java/org/ilisi/backend/controller/PosteController.java
  backend/src/main/java/org/ilisi/backend/dto/AuthRequestDTO.java
  backend/src/main/java/org/ilisi/backend/dto/CommentDto.java
  backend/src/main/java/org/ilisi/backend/dto/PosteDto.java
  backend/src/main/java/org/ilisi/backend/mapper/CommentMapper.java
  backend/src/main/java/org/ilisi/backend/mapper/PosteMapper.java
  backend/src/main/java/org/ilisi/backend/model/Comment.java
  backend/src/main/java/org/ilisi/backend/model/Poste.java
  backend/src/main/java/org/ilisi/backend/model/Session.java
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/model/User.java
  backend/src/main/java/org/ilisi/backend/repository/CommentRepository.java
  backend/src/main/java/org/ilisi/backend/repository/PosteRepository.java
  backend/src/main/java/org/ilisi/backend/service/PosteService.java
  backend/src/test/java/org/ilisi/backend/controller/PosteControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/ReviewControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/service/PosteServiceTests.java
  backend/src/test/java/org/ilisi/backend/service/ReviewServiceTests.java
Labels: good first issue

#58 43 add email service
  .gitignore
  backend/pom.xml
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/email/EmailConfig.java
  backend/src/main/java/org/ilisi/backend/email/EmailProperties.java
  backend/src/main/java/org/ilisi/backend/email/EmailService.java
  backend/src/main/java/org/ilisi/backend/service/StudentService.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/org/ilisi/backend/controller/StudentControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/service/StudentServiceTests.java
Labels: good first issue

#59 55 add institut reviews
  backend/compose.yaml
  backend/src/main/java/org/ilisi/backend/config/JacksonConfiguration.java
  backend/src/main/java/org/ilisi/backend/config/UserDeserializer.java
  backend/src/main/java/org/ilisi/backend/controller/InstitutController.java
  backend/src/main/java/org/ilisi/backend/controller/PosteController.java
  backend/src/main/java/org/ilisi/backend/controller/ReviewController.java
  backend/src/main/java/org/ilisi/backend/dto/AuthRequestDTO.java
  backend/src/main/java/org/ilisi/backend/dto/CommentDto.java
  backend/src/main/java/org/ilisi/backend/dto/PosteDto.java
  backend/src/main/java/org/ilisi/backend/dto/ReviewDto.java
  backend/src/main/java/org/ilisi/backend/mapper/CommentMapper.java
  backend/src/main/java/org/ilisi/backend/mapper/PosteMapper.java
  backend/src/main/java/org/ilisi/backend/mapper/ReviewMapper.java
  backend/src/main/java/org/ilisi/backend/model/Comment.java
  backend/src/main/java/org/ilisi/backend/model/Institut.java
  backend/src/main/java/org/ilisi/backend/model/Poste.java
  backend/src/main/java/org/ilisi/backend/model/Review.java
  backend/src/main/java/org/ilisi/backend/model/Session.java
  backend/src/main/java/org/ilisi/backend/model/Student.java
  backend/src/main/java/org/ilisi/backend/model/User.java
  backend/src/main/java/org/ilisi/backend/repository/CommentRepository.java
  backend/src/main/java/org/ilisi/backend/repository/PosteRepository.java
  backend/src/main/java/org/ilisi/backend/repository/ReviewRepository.java
  backend/src/main/java/org/ilisi/backend/service/InstitutService.java
  backend/src/main/java/org/ilisi/backend/service/PosteService.java
  backend/src/main/java/org/ilisi/backend/service/ReviewService.java
  backend/src/test/java/org/ilisi/backend/controller/PosteControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/ReviewControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/service/PosteServiceTests.java
  backend/src/test/java/org/ilisi/backend/service/ReviewServiceTests.java
  frontend/src/assets/images/user.png
Labels: good first issue

#60 53 add image upload
  frontend/src/app/components/education-modal/education-modal.component.html
  frontend/src/app/components/education-modal/education-modal.component.ts
  frontend/src/app/components/experience-modal/experience-modal.component.html
  frontend/src/app/components/experience-modal/experience-modal.component.ts
  frontend/src/app/components/profile-form-modal/profile-form-modal.component.html
  frontend/src/app/components/profile-form-modal/profile-form-modal.component.ts
  frontend/src/app/models/institut.ts
  frontend/src/app/models/user.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/student-profile.service.ts
  frontend/src/assets/images/Default_pfp.svg.png
Labels: enhancement

#66 #65 routes guards done & user stored globally.
  backend/src/main/java/org/ilisi/backend/service/AuthenticationService.java
  frontend/src/app/app.config.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/components/layout/layout.component.html
  frontend/src/app/components/layout/layout.component.ts
  frontend/src/app/guards/manager.guard.spec.ts
  frontend/src/app/guards/manager.guard.ts
  frontend/src/app/guards/student.guard.spec.ts
  frontend/src/app/guards/student.guard.ts
  frontend/src/app/models/token.ts
  frontend/src/app/models/user.ts
  frontend/src/app/pages/login/login.component.ts
  frontend/src/app/services/auth.service.ts
Labels: good first issue

#68 67 make companie reviews page dynamic
  frontend/src/app/app.routes.ts
  frontend/src/app/models/institut.ts
  frontend/src/app/models/review.ts
  frontend/src/app/pages/company-reviews/company-reviews.component.html
  frontend/src/app/pages/company-reviews/company-reviews.component.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/institut.service.ts
  frontend/src/app/services/review.service.spec.ts
  frontend/src/app/services/review.service.ts
Labels: good first issue

#69 63 add static companie reviews page
  frontend/src/app/app.routes.ts
  frontend/src/app/models/institut.ts
  frontend/src/app/models/review.ts
  frontend/src/app/pages/company-reviews/company-reviews.component.css
  frontend/src/app/pages/company-reviews/company-reviews.component.html
  frontend/src/app/pages/company-reviews/company-reviews.component.spec.ts
  frontend/src/app/pages/company-reviews/company-reviews.component.ts
  frontend/src/app/pages/company-reviews/navbar-data.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/institut.service.ts
  frontend/src/app/services/review.service.spec.ts
  frontend/src/app/services/review.service.ts
Labels: good first issue

#71 62 add posts to frontend
  .env
  frontend/src/app/app.routes.ts
  frontend/src/app/components/layout/layout.component.html
  frontend/src/app/components/post-modal/post-modal.component.css
  frontend/src/app/components/post-modal/post-modal.component.html
  frontend/src/app/components/post-modal/post-modal.component.spec.ts
  frontend/src/app/components/post-modal/post-modal.component.ts
  frontend/src/app/components/post/post.component.css
  frontend/src/app/components/post/post.component.html
  frontend/src/app/components/post/post.component.spec.ts
  frontend/src/app/components/post/post.component.ts
  frontend/src/app/components/profile/profile.component.html
  frontend/src/app/models/comment.ts
  frontend/src/app/models/poste.ts
  frontend/src/app/pages/home/home.component.html
  frontend/src/app/pages/home/home.component.ts
  frontend/src/app/pages/post-forum/navbar-data.ts
  frontend/src/app/pages/post-forum/post-forum.component.css
  frontend/src/app/pages/post-forum/post-forum.component.html
  frontend/src/app/pages/post-forum/post-forum.component.spec.ts
  frontend/src/app/pages/post-forum/post-forum.component.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/services/post.service.spec.ts
  frontend/src/app/services/post.service.ts
  frontend/src/assets/images/post1.png
  package-lock.json
Labels: integration

#72 64 implement image upload backend
  backend/src/main/java/org/ilisi/backend/BackendApplication.java
  backend/src/main/java/org/ilisi/backend/config/StorageProperties.java
  backend/src/main/java/org/ilisi/backend/controller/FileUploadController.java
  backend/src/main/java/org/ilisi/backend/controller/InstitutController.java
  backend/src/main/java/org/ilisi/backend/controller/StudentProfileController.java
  backend/src/main/java/org/ilisi/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/org/ilisi/backend/exception/StorageException.java
  backend/src/main/java/org/ilisi/backend/exception/StorageFileNotFoundException.java
  backend/src/main/java/org/ilisi/backend/model/Institut.java
  backend/src/main/java/org/ilisi/backend/model/User.java
  backend/src/main/java/org/ilisi/backend/security/SecurityConfig.java
  backend/src/main/java/org/ilisi/backend/service/FileSystemStorageService.java
  backend/src/main/java/org/ilisi/backend/service/ProfileService.java
  backend/src/main/java/org/ilisi/backend/service/StorageService.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/org/ilisi/backend/BackendApplicationTests.java
  backend/src/test/java/org/ilisi/backend/controller/AuthenticationControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/PosteControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/ReviewControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/StudentControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/controller/StudentProfileControllerIntegrationTests.java
  backend/src/test/java/org/ilisi/backend/specification/StudentSpecsTests.java
  frontend/src/app/components/experience-modal/experience-modal.component.ts
  frontend/src/app/components/profile-form-modal/profile-form-modal.component.ts
  frontend/src/app/models/institut.ts
  frontend/src/app/models/student.ts
  frontend/src/app/models/user.ts
  frontend/src/app/pages/student-profile/student-profile.component.html
  frontend/src/app/pages/student-profile/student-profile.component.ts
  frontend/src/app/services/file-upload.service.spec.ts
  frontend/src/app/services/file-upload.service.ts
  frontend/src/app/services/student-profile.service.ts
Labels: integration
